### ISSUE TITLE
UPGRADE - PROJECT

### ISSUE THREAD

**Issue by odyright** [Odigietony/school-management-system#1]
hello , i want to great you for your work. But since C# is better with UWP (universal windows platform) can we plan to perform this project?... i hope you will aggree. Thx

**Comment by Odigietony** [comment]
Sounds good. What do have in mind?

**Comment by odyright** [comment]
thx for your good mind. we can use as i said:
UWP with MVVM pattern such as MvvMLight. 
make this application available as Client-Server (that will required credentials logins)
etc...

**Comment by Odigietony** [comment]
Okay, but I will be unavailable for 3 weeks as I'm about to write my final exams at the university. So I beg your patience as this is something I'm very interested in being a part of. 

Cheers!

**Comment by odyright** [comment]
ok i'll. In the meantime i sent to you an invite! you can throw a look...but there are some errors.

**Comment by Odigietony** [comment]
Hey Dan, I've just completed my final exams. I'm available now.
Still looking to work on the School Management System?

**Comment by odyright** [comment]
yeah! i'm available... sry ! i was busy last time.

**Comment by Odigietony** [comment]
No worries... So when do we start?

**Comment by odyright** [comment]
i soon as possible but GitHub doesn't allow private repo without fees. i was thiking about bitbucket..!

**Comment by odyright** [comment]
https://bitbucket.org/odylight/systumecisample

**Comment by Odigietony** [comment]
Sorry it took so long, Just registered to gitbucket

**Comment by odyright** [comment]
ok
